### ISSUE TITLE
Envoy V5 not https?

### ISSUE THREAD

**Issue by radioelf** [ZimbiX/amber-enphase-zero-export-switcher-tool#5]
Hi.
I'm trying to change the network profile with your application locally and I'm getting the following error: "Connection refused - connect(2) for 192.168.0.60:443" I can access locally via http://192.168.1.60/installer/setup/home and navigate to http://192.168.1.60/installer/setup/home#microinverters/status/profile to change the network profile without any issues, but not through https. My envoy does not allow access via https (443). If I modify the code to access via http, I get the error "Error: wrong array length at 2 (expected 2, was 3)". Do you have the same issue with envoy V5 (Software Version  D5.0.62)? Thank you.

**Comment by ZimbiX** [comment]
Oh sorry, I forgot V5 didn't support HTTPS! I could add another config option to select whether HTTPS is used.

> If I modify the code to access via http, I get the error "Error: wrong array length at 2 (expected 2, was 3)".

Are you using the latest code (`git pull`)? Have you installed the latest gems (`bundle`)? And is this the change you made?

```diff
diff --git a/lib/zest/enphase/client.rb b/lib/zest/enphase/client.rb
index bdb653c..c19ed7c 100644
--- a/lib/zest/enphase/client.rb
+++ b/lib/zest/enphase/client.rb
@@ -41,7 +41,7 @@ module Zest
       end
 
       def base_url
-        "https://#{envoy_ip}"
+        "http://#{envoy_ip}"
       end
     end
   end
```

I would've thought that would work. I can't think what your error would be from. A backtrace would help if you could post that? I don't have an Envoy on V5 to test with. With the above change, if I configure my Zest for V5 against my V7 Envoy, I don't get an error (nor even - I've just realised - the error I'd expect, which is a separate problem!)

Edit: Your profile says you're in Spain - are you using Amber there? =P

**Comment by radioelf** [comment]
Hi, yes, I'm using the latest code (git pull). I've made some small modifications to perform the profile change test, as I'm not using Amber. Once I successfully change the network profile, I'll adapt the code for my network operator. The current changes are:

    Modified /amber-enphase-zero-export-switcher-tool-master/Gemfile: Changed 'ruby >= 3.0.2' to 'ruby >= 3.1.0'.
    Modified /amber-enphase-zero-export-switcher-tool-master/lib/zest/enphase/client.rb: Changed "https://#{envoy_ip}" to "http://#{envoy_ip}".
    Modified /amber-enphase-zero-export-switcher-tool-master/lib/zest/amber/client.rb: Changed cost = current_prices.export.cents_per_kwh to cost = 0.03.

.env contains:
ZEST_LOG_LEVEL=debug
ZEST_STATUS_FILE=.status
ZEST_COMMAND_TO_RUN_AFTER_SWITCHING_GRID_PROFILE=

ZEST_AMBER_TOKEN=unused
ZEST_AMBER_SITE_ID=unused
ZEST_AMBER_POLL_INTERVAL_SECONDS=5

ZEST_AMBER_EXPORT_ZERO=1

ZEST_ENPHASE_ENVOY_IP=192.168.1.60

ZEST_ENPHASE_ENVOY_FIRMWARE_VERSION=5

#- For firmware v4/v5:
ZEST_ENPHASE_ENVOY_INSTALLER_USERNAME=installer
ZEST_ENPHASE_ENVOY_INSTALLER_PASSWORD=xxxxxxx

#- For version 7 unused
ZEST_ENPHASE_ENLIGHTEN_USERNAME=unused
ZEST_ENPHASE_ENLIGHTEN_PASSWOR=unused
ZEST_ENPHASE_ENVOY_SERIAL=unused
ZEST_ENPHASE_ENVOY_ACCESS_TOKEN=Nunused

ZEST_ENPHASE_ENVOY_GRID_PROFILE_NAME_NORMAL_EXPORT="EN 50549-1:2019 Spain:1.2.1"
ZEST_ENPHASE_ENVOY_GRID_PROFILE_NAME_ZERO_EXPORT="EN 50549-1:2019 - No Export:1.2.1"

And in console I get:
I -- Amber says exporting energy to the grid would currently cost me: 0.03 c/kWh
I -- Making HTTP request to set export limit to zero...
Error: wrong array length at 2 (expected 2, was 3)

Thank you again.

**Comment by ZimbiX** [comment]
I'm confused by your first change - at the latest commit (fa37a5b), that one's already been made. So something about what you've said doesn't add up.

The other changes seem fine. btw, an easy way to show a set of the changes is by copying the output of `git diff` - and then pasting it here as a code block with diff syntax, like this:

    ```diff
    the output goes here
    ```

(that's what I've done below)

I notice you have a typo in `ZEST_ENPHASE_ENLIGHTEN_PASSWOR`, but that env var's not used for V5, so it wouldn't be an issue.

Given the `Error: ` prefix, I think the error is being logged from [here](https://github.com/ZimbiX/amber-enphase-zero-export-switcher-tool/blob/fa37a5bf7f23a1f22ccdfe0bd9c8170f92ac8bea/zest.rb#L76), but I would have thought the backtrace should've also been logged from there. To try to get the backtrace, comment out the rescue block so it actually raises the exception; like so:

```diff
diff --git a/zest.rb b/zest.rb
index 2f89a31..8ada7d9 100755
--- a/zest.rb
+++ b/zest.rb
@@ -66,15 +66,15 @@ enphase_manager = Zest::Enphase::Manager.new(
 amber_poll_interval_seconds = Float(ENV.fetch('ZEST_AMBER_POLL_INTERVAL_SECONDS'))
 
 loop do
-  begin
+  # begin
     if amber_client.costs_me_to_export?
       enphase_manager.set_export_limit_to_zero
     else
       enphase_manager.set_export_limit_to_normal
     end
-  rescue => e
-    puts "Error: #{e}", e.backtrace
-  end
+  # rescue => e
+  #   puts "Error: #{e}", e.backtrace
+  # end
   puts
   sleep amber_poll_interval_seconds
 end
```

Another thing you can try, from the readme:

> To debug HTTP issues, [set the `HTTPX_DEBUG` environment variable](https://honeyryderchuck.gitlab.io/httpx/wiki/Debugging).

**Comment by radioelf** [comment]
Hello again ZimbiX. you're right, the first change is not correct, it should be:  'ruby >= 3.1.0' to 'ruby >= 3.0.2'. My version is: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]

In ZEST_ENPHASE_ENVOY_INSTALLER_PASSWORD= I have used xxxxx and not the real password, but I use the one I use to access the page http://192.168.1.60/installer/setup/home#microinverters/status/profile.

I have made the modification you indicated and now this is my console output:

```
I -- Amber says exporting energy to the grid would currently cost me: 0.03 c/kWh
I -- Making HTTP request to set export limit to zero...
/var/lib/gems/3.0.0/gems/httpx-1.2.0/lib/httpx/plugins/auth/digest.rb:33:in `to_h': wrong array length at 2 (expected 2, was 3) (ArgumentError)
	from /var/lib/gems/3.0.0/gems/httpx-1.2.0/lib/httpx/plugins/auth/digest.rb:33:in `generate_header'
	from /var/lib/gems/3.0.0/gems/httpx-1.2.0/lib/httpx/plugins/auth/digest.rb:23:in `authenticate'
	from /var/lib/gems/3.0.0/gems/httpx-1.2.0/lib/httpx/plugins/digest_auth.rb:50:in `block in send_requests'
	from /var/lib/gems/3.0.0/gems/httpx-1.2.0/lib/httpx/plugins/digest_auth.rb:39:in `each'
	from /var/lib/gems/3.0.0/gems/httpx-1.2.0/lib/httpx/plugins/digest_auth.rb:39:in `flat_map'
	from /var/lib/gems/3.0.0/gems/httpx-1.2.0/lib/httpx/plugins/digest_auth.rb:39:in `send_requests'
	from /var/lib/gems/3.0.0/gems/httpx-1.2.0/lib/httpx/session.rb:70:in `request'
	from /var/lib/gems/3.0.0/gems/httpx-1.2.0/lib/httpx/chainable.rb:8:in `put'
	from /home/joan/amber-enphase-zero-export-switcher-tool-master/lib/zest/enphase/client.rb:16:in `set_current_grid_profile'
	from /home/joan/amber-enphase-zero-export-switcher-tool-master/lib/zest/enphase/manager.rb:41:in 'set_export_limit_to_zero'
	from zest.rb:94:in 'block in <main>'

```
Very grateful for your help.

**Comment by ZimbiX** [comment]
Thanks for the backtrace. I can't see an issue with how it's using HTTPX's digest auth, which looks to me to [match the HTTPX wiki](https://honeyryderchuck.gitlab.io/httpx/wiki/Auth#digest-auth):

https://github.com/ZimbiX/amber-enphase-zero-export-switcher-tool/blob/2cf8c9186e6290aa1e7210713d14d7de22967837/lib/zest/enphase/installer_auth/firmware_v5/credentials_auth.rb#L17-L19

Zest is not compatible with Ruby 3.0, due to use of a [language feature introduced in Ruby 3.1](https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/#:~:text=foo(x%3A%2C%20y%3A)%20is%20syntax%20sugar%20for%20foo(x%3A%20x%2C%20y%3A%20y)):

> - `foo(x:, y:)` is syntax sugar for `foo(x: x, y: y)`.

If you try to run it on Ruby 3.0, you should see:

```
➜ ./zest.rb
./zest.rb:26: syntax error, unexpected ','
      logger:,
./zest.rb:27: syntax error, unexpected ',', expecting `end'
...ASE_ENVOY_INSTALLER_USERNAME'),
./zest.rb:28: syntax error, unexpected ',', expecting end-of-input
...ASE_ENVOY_INSTALLER_PASSWORD'),
```

[Ruby's support for 3.0 ends in just over two weeks btw](https://endoflife.date/ruby) (wow, that makes me feel old!).

I don't understand how it's working for you at all. I suspect you've changed more code to get it running on Ruby 3.0?

I've just pushed a commit to update the gems - does that (or `bundle update` yourself) help you at all?

I think if you could push all your code to a fork, I'd be able to help you more easily.

**Comment by ZimbiX** [comment]
To sanity check, does this cURL command work to change the profile? (replace `xxxxxxx` with your installer password)

```bash
curl -sSN -X PUT http://192.168.1.60/installer/agf/set_profile.json --digest -u installer:xxxxxxx -H 'Content-Type: application/json' -d '{"selected_profile":"EN 50549-1:2019 - No Export:1.2.1"}'
```

If so, what about this minimal Ruby script equivalent? Save it as `test.rb` and run `HTTPX_DEBUG=2 ruby test.rb`

```ruby
require 'httpx'
HTTPX
  .with_headers('Accept' => 'application/json')
  .plugin(:digest_auth)
  .digest_auth('installer', 'xxxxxxx')
  .put('http://192.168.1.60/installer/agf/set_profile.json', json: { selected_profile: 'EN 50549-1:2019 - No Export:1.2.1' })
```

If HTTPX is the issue, maybe you could try a different Ruby HTTP library.

**Comment by radioelf** [comment]
Hi, to simplify, I've updated Ruby to 3.1.0p0 (2021-12-25 revision fb4df44d16) [x86_64-linux] and calling HTTPX_DEBUG=2 ruby test.rb, I'm getting
```
resolver: answer A 192.168.1.60: [#<IPAddr: IPv4:192.168.1.60/255.255.255.255>]
 idle -> idle
Connected to 192.168.1.60 (#5)
<- HEADLINE: "PUT /installer/agf/set_profile.json HTTP/1.1"
<- HEADER: Accept: application/json
<- HEADER: User-Agent: httpx.rb/1.2.3
<- HEADER: Accept-Encoding: gzip, deflate
<- HEADER: Content-Type: application/json; charset=utf-8
<- HEADER: Content-Length: 56
<- HEADER: Connection: close
<- HEADER: Host: 192.168.1.60
<- 
<- DATA: 56 bytes...
<- "{\"selected_profile\":\"EN 50549-1:2019 - No Export:1.2.1\"}"
WRITE: 296 bytes...
READ: 246 bytes...
parsing begins
headers received
-> HEADLINE: 401 HTTP/1.1
-> HEADER: www-authenticate: Digest qop="auth", realm="enphaseenergy.com", nonce="wPLznPJq1ZTNMuyX4KuTrotGqT0="
-> HEADER: connection: close
-> HEADER: content-type: text/html
-> HEADER: content-length: 51
-> DATA: 51 bytes...
-> "<html><body><h2>401 Unauthorized</h2></body></html>"
parsing complete
192.168.1.60 connected -> closed
/home/joan/.rvm/gems/ruby-3.1.0/gems/httpx-1.2.3/lib/httpx/plugins/auth/digest.rb:33:in `to_h': wrong array length at 2 (expected 2, was 3) (ArgumentError)
	from /home/joan/.rvm/gems/ruby-3.1.0/gems/httpx-1.2.3/lib/httpx/plugins/auth/digest.rb:33:in `generate_header'
	from /home/joan/.rvm/gems/ruby-3.1.0/gems/httpx-1.2.3/lib/httpx/plugins/auth/digest.rb:23:in `authenticate'
	from /home/joan/.rvm/gems/ruby-3.1.0/gems/httpx-1.2.3/lib/httpx/plugins/digest_auth.rb:50:in `block in send_requests'
	from /home/joan/.rvm/gems/ruby-3.1.0/gems/httpx-1.2.3/lib/httpx/plugins/digest_auth.rb:39:in `each'
	from /home/joan/.rvm/gems/ruby-3.1.0/gems/httpx-1.2.3/lib/httpx/plugins/digest_auth.rb:39:in `flat_map'
	from /home/joan/.rvm/gems/ruby-3.1.0/gems/httpx-1.2.3/lib/httpx/plugins/digest_auth.rb:39:in `send_requests'
	from /home/joan/.rvm/gems/ruby-3.1.0/gems/httpx-1.2.3/lib/httpx/session.rb:72:in `request'
	from /home/joan/.rvm/gems/ruby-3.1.0/gems/httpx-1.2.3/lib/httpx/chainable.rb:10:in `put'
	from test.rb:6:in `<main>'
```
I see that the response is 401 Unauthorized, but if I execute:
```
curl -sSN -X PUT http://192.168.1.60/installer/agf/set_profile.json --digest -u installer:xxxxxxx -H 'Content-Type: application/json' -d '{"selected_profile":"EN 50549-1:2019 - No Export:1.2.1"}'
```
It works correctly and the profile is changed in the Envoy. Sorry for my lack of knowledge in Ruby as it's my first time using it, and very grateful again for the help. Since I see that it's not a problem with the code, if you think it's appropriate, I'll close the issue.

**Comment by ZimbiX** [comment]
Somebody else encountered firmware v4 not supporting HTTPS - I didn't realise I'd forgotten to address that after you raised it here. Done in c3088e82a0c986edba5d174253471d8317b9c711
